# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, db_index=True, max_length=255, unique=True),
        ),
    ]
