# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='created_date',
            new_name='created_at',
        ),
    ]
